# Generated by Django 4.1.2 on 2022-10-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
    ]
