# Generated by Django 4.1.2 on 2022-10-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_super_type_super_super_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type_id',
            new_name='super_type',
        ),
    ]
